version: '3.1'

networks:
  analytic-net:
    driver: bridge
    external: true

services:
  be:
    image: be:latest
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: be
    deploy:
      resources:
        limits:
          cpus: '0.01'
          memory: 50M
    ports:
      - 9990:9990
    networks:
      - analytic-net
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - KAFKA_BROKER=${KAFKA_BROKER}
      - KAFKA_TOPIC=${KAFKA_TOPIC}
    depends_on:
      - db
