version: '3.3'

networks:
  analytic-net:
    driver: bridge
    external: true

services:
  starrocks-fe:
    image: starrocks-fe.3.2.8
    container_name: starrocks-fe
    build:
      context: ./image/fe
      dockerfile: Dockerfile.fe
    volumes:
      - st-fe:/opt/starrocks/fe
    ports:
      - 8038:8030
      - 9038:9030
    networks:
      - analytic-net
  
  starrocks-be:
    image: starrocks-be.3.2.8
    container_name: starrocks-be
    build:
      context: ./image/be
      dockerfile: Dockerfile.be
    volumes:
      - st-be:/opt/starrocks/be
    ports:
      - 8048:8040
      - 9068:9060
    networks:
      - analytic-net
    depends_on:
      - starrocks-fe

  starrocks-cn:
    image: starrocks-cn.3.2.8
    container_name: starrocks-cn
    build:
      context: ./image/cn
      dockerfile: Dockerfile.cn
    volumes:
      - st-cn:/opt/starrocks/be
    networks:
      - analytic-net
    depends_on:
      - starrocks-be

volumes:
  st-fe:
    external: true
  st-be:
    external: true
  st-cn:
    external: true
