version: '3.7'

networks:
  analytic-net:
    driver: bridge
    external: true

services:
  zookeeper:
    image: zookeeper
    container_name: zookeeper
    restart: always
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zookeeper:2888:3888;2181
    networks:
      - analytic-net 
    depends_on:
      - postgres
  
  kafka:
    image: kafka-server:$KAFKA_VERSION
    build:
      context: ./images/server
      args:
        - KAFKA_VERSION=$KAFKA_VERSION
    container_name: kafka-server
    restart: always
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
    networks:
      - analytic-net
