version: '3.1'

networks:
  analytic-net:
    driver: bridge
    external: true

services:
  postgres:
    image: postgres:15.3
    container_name: db 
    ports:
      - 5433:5432
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD} 
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - analytic-net
